# Generated by Django 5.1 on 2024-10-30 17:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BicycleParkingStandSDCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featureID', models.IntegerField()),
                ('featureID_internal', models.IntegerField(default=0)),
                ('globalID', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('senior_stand', models.IntegerField()),
                ('junior_stand', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.RenameField(
            model_name='bicyclemaintenancestandsdcc',
            old_name='objectid',
            new_name='featureID',
        ),
        migrations.AddField(
            model_name='bicyclemaintenancestandsdcc',
            name='featureID_internal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
