# Generated by Django 5.1 on 2024-10-31 14:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BicycleMaintenanceStandSDCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featureID', models.IntegerField()),
                ('featureID_internal', models.IntegerField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('area', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='BicycleParkingStandSDCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featureID', models.IntegerField()),
                ('featureID_internal', models.IntegerField(default=0)),
                ('globalID', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('senior_stand', models.IntegerField()),
                ('junior_stand', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='BikeMaintenanceStandDLR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featureID', models.IntegerField()),
                ('featureID_internal', models.IntegerField()),
                ('maintenance_point', models.CharField(max_length=3)),
                ('covered', models.CharField(max_length=3)),
                ('confirmed', models.CharField(max_length=3)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='BikeMaintenanceStandFCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featureID', models.IntegerField()),
                ('featureID_internal', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('public_stands', models.IntegerField(blank=True, default=0, null=True)),
                ('private_stands', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.CharField(max_length=20)),
                ('stand_type', models.CharField(max_length=100)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='CyclewaysDublinMetro',
            fields=[
                ('featureID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('twoway', models.CharField(max_length=1)),
                ('bollard_protected', models.CharField(max_length=1)),
                ('shape_length', models.FloatField()),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='CyclewaysSDCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featureID', models.IntegerField()),
                ('layer', models.CharField(max_length=255)),
                ('colour', models.IntegerField()),
                ('linetype', models.CharField(max_length=50, null=True)),
                ('linewt', models.IntegerField()),
                ('refname', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
        ),
    ]
