# Generated by Django 5.1 on 2024-11-05 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cyclewayssdcc',
            old_name='layer',
            new_name='name',
        ),
    ]
