# Generated by Django 5.1.4 on 2024-12-17 14:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_rename_layer_cyclewayssdcc_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DublinCityParkingStand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.CharField(max_length=100, unique=True)),
                ('bicycle_parking', models.CharField(blank=True, max_length=50, null=True)),
                ('covered', models.CharField(blank=True, max_length=10, null=True)),
                ('capacity', models.CharField(blank=True, max_length=5, null=True)),
                ('surveillance', models.CharField(blank=True, max_length=10, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('fee', models.CharField(blank=True, max_length=10, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
